name: YT build
on:
  push:
    branches: [ "Vip" ]
  pull_request:
    branches: [ "Vip" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run code
        run: |
          chmod 777 install.sh
          . install.sh
