name: YT build
on: 
  push:
    branches: [ "Vip" ]
  pull_request:
    branches: [ "Vip" ]
  workflow_dispatch:
  issues:
  pull_request_target:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run code
        run: |
          chmod 777 install.sh
          . install.sh
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: YouTube.zip
          path: Up/*
          retention-days: 5
      - name: Upload json
        uses: softprops/action-gh-release@v1
        with:
          tag: Up
          name: Update
          tag_name: Up
          files: Up*.json
          prerelease: true
      - name: Upload File
        uses: softprops/action-gh-release@v1
        with:
          tag: YT
          name: YT-AT
          tag_name: Download
          files: Up/*
